### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by bjarkehs** [trifork/trireg#5]
Ease installation by providing Homebrew

**Comment by runesl** [comment]
Or rpm :)

**Comment by mwl** [comment]
@bjarkehs I hardly doubt [Homebrew](Homebrew/homebrew) will accept tools like this. So we'll have to set up our own Tab. You are more than welcome to do so.

**Comment by mwl** [comment]
@rsltrifork We are talking about _one_ file…
