### ISSUE TITLE
TriregFile

### ISSUE THREAD

**Issue by bjarkehs** [trifork/trireg#6]
Maybe instead of requiring an environment loader it would be a good idea to have a configuration file like it's common within the Ruby world. So you would have a TriregFile with the contents. I'm not sure how easy this is with Go, but it's at least a very common theme within tools made for iOS. (See tools like [Fastlane](https://github.com/fastlane/fastlane) and [CocoaPods](https://cocoapods.org/)

**Comment by mongrelion** [comment]
We could use some standard configuration file format. JSON is file but I think it's more configuration oriented https://github.com/toml-lang/toml

**Comment by mwl** [comment]
Personally I don't see a great use for this which can't be achieved with, for instance, [direnv](direnv/direnv).

Anyway I'm happy to accept a pull request, as long as the file isn't called `triregfile` (everybody knows it's a file).

**Comment by mongrelion** [comment]
Late to the discussion since the thread has been closed but would you take something like `~/.triregrc`?

**Comment by mwl** [comment]
`*rc` usually means a script?

I think best practice is something like this, where last hit wins
1. `/etc/trireg.conf`
2. `~/.trireg.conf`
3. `./.trireg.conf`
4. `TRIREG_*` environment variables
5. Command line arguments

I'm not exactly sure where sure where the environment variables fits in. Honestly I think that tools like direnv are assisting in solving this problem the best way anyway.

**Comment by bjarkehs** [comment]
The reason I suggested using a file is that direnv requires the user to install something beside just trireg-cli. It means that customizing is more tricky than necessary. I'm running direnv right now, so it's not a huge deal, but I would prefer a configuration file. (Name was based on configuration file names for the Fastlane suite of tools)

**Comment by mongrelion** [comment]
didn't know that `*rc` meant script. I think it's very common for cli apps (vim, rubygems, npm, nvm, etc.) to have a `*rc` file in the home folder kind of thing. I would not go for something so global like /etc/triregrc as I don't think that this would even be used in such a scope.
