### ISSUE TITLE
multiple-value gopass.GetPasswd() in single-value context

### ISSUE THREAD

**Issue by runesl** [trifork/trireg#8]
I have no idea, how to build or run trireg-cli, but it seems to always fail:

rsl@nohostname:~/apps/trireg-cli-0.4> go run trireg.go 
# command-line-arguments

./trireg.go:49: multiple-value gopass.GetPasswd() in single-value context

**Comment by mwl** [comment]
Sounds like you haven't installed the required modules

```
go get github.com/codegangsta/cli
go get github.com/howeyc/gopass
```
